### PR TITLE
AnnePro2 EEPROM support

### PR DESCRIPTION
**Pull request by tech2077**
### List of changes
- Add HT32 SPI Master driver with similar API to spi_master.c
- Add basic EEPROM library
- Added persistent LED profiles
- Added rules.mk ANNEPRO2_EEPROM = (yes|no) option
- When eeprom makefile feature is not selected, eeprom functions default to dummy versions
- Example keymap for using persistent eeprom and led profiles

### CODE REVIEW

**Comment by Codetector1374** [comment]
Hi, Would you be interested in adding the HT32 SPI master driver to the chibiOS-contrib project? I think it would better fit over there. Sorry for taking this long to get around to this review.

(There's some code there for the HT32F165x series you can probably reference.)

https://github.com/OpenAnnePro/ChibiOS-Contrib/tree/feat-ht32_support

**Comment by Codetector1374** [comment]
Also it would be nice to probably split this into multiple PRs by function (separate EEPROM stuff from the profile commands). Really thanks for all of this code. It just seems like a bit too much has changed in one single PR. Let me know if you have any questions

**Comment by tech2077** [comment]
Yeah, I can split it up into a few PRs, one for EEPROM and one for the profile commands. The spi driver is probably more appropriately integrated into the spi_master drive in qmk, it's roughly the same level as the code for the STM32 in that driver.

**Comment by Codetector1374** [comment]
Okay sounds good to me

**Pull request closed without merging**
